trigger:
- master

pool:
  vmImage: 'windows-latest'
  
steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'

#Add sonarcloud Prepare

- task: SonarCloudPrepare@1
  displayName: 'Prepare SonarCloud Analysis'
  inputs:
    SonarCloud: 'sonar'
    organization: 'myproject-key'
    scannerMode: 'MSBuild'
    projectKey: 'myproject-key'
    projectName: 'myproject-key'
    projectVersion: '$(build.buildnumber)'
    extraProperties:
      sonar.cs.opencover.reportsPaths=$(build.sourcesdirectory)/TestResults/Coverage/coverage.opencover.xml
      sonar.exclusions=**/wwwroot/lib/**

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)/bin'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# SonarCloud Analyze
- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud Analysis'

# SonarCloud Publish
- task: SonarCloudPublish@1
  displayName: 'Publish SonarCloud quality gate results'

- script: echo "All done"
  displayName: 'Success'
