trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- script: echo Hello, World v2
  displayName: 'Run a oneline script v2'
  
- script: |
    echo Add a multiline script
    echo Add one more line v2
  displayName: 'Run a multiline script v2'
