trigger:
- master
  
pool:
  vmImage: 'windows-latest'
  
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '140cfa43-4398-435f-8b68-9c169f45e0ec'

- task: SonarCloudPrepare@1
  displayName: 'Prepare Sonarcloud Analysis'
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'myproject-key'
    scannerMode: 'MSBuild'
    projectKey: 'mykey'
    projectName: 'myproject-key'
    projectVersion: '$(build.buildnumber)'
    extraProperties:
      sonar.cs.opencover.reportsPaths=$(build.sourcesdirectory)/TestResults/Coverage/coverage.opencover.xml
      sonar.exclusions=**/wwwroot/lib/**

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Debug'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*[Tt]ests.csproj'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)/bin'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud Analysis'

- task: SonarCloudPublish@1
  displayName: 'Publish SonarCloud Analysis'
  inputs:
    pollingTimeoutSec: '300'