trigger:
- master
  
pool:
  vmImage: 'ubuntu-latest'
  
steps:
- script: echo Hello,World
  displayName: 'Task One'
  
- script: |
    echo Welcome to Devops
	  echo multiline
  displayName: 'Multiline Task'